package model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "adid", Admin.class);
		arp.addMapping("choice_question", "c_id", ChoiceQuestion.class);
		arp.addMapping("fill_question", "f_id", FillQuestion.class);
		arp.addMapping("history", "id", History.class);
		arp.addMapping("interviewer", "tid", Interviewer.class);
		arp.addMapping("student", "sid", Student.class);
	}
}

