package model;

import model.base.BaseFillQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FillQuestion extends BaseFillQuestion<FillQuestion> {
	public static final FillQuestion dao = new FillQuestion().dao();
}
