package model;

import model.base.BaseHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class History extends BaseHistory<History> {
	public static final History dao = new History().dao();
}
