package model;

import model.base.BaseInterviewer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Interviewer extends BaseInterviewer<Interviewer> {
	public static final Interviewer dao = new Interviewer().dao();
}
