package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInterviewer<M extends BaseInterviewer<M>> extends Model<M> implements IBean {

	public M setTid(java.lang.String tid) {
		set("tid", tid);
		return (M)this;
	}

	public java.lang.String getTid() {
		return get("tid");
	}

	public M setTname(java.lang.String tname) {
		set("tname", tname);
		return (M)this;
	}

	public java.lang.String getTname() {
		return get("tname");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public M setCardnumber(java.lang.String cardnumber) {
		set("cardnumber", cardnumber);
		return (M)this;
	}

	public java.lang.String getCardnumber() {
		return get("cardnumber");
	}

	public M setPwd(java.lang.String pwd) {
		set("pwd", pwd);
		return (M)this;
	}

	public java.lang.String getPwd() {
		return get("pwd");
	}

	public M setDepartment(java.lang.String department) {
		set("department", department);
		return (M)this;
	}

	public java.lang.String getDepartment() {
		return get("department");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

}
