package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	public M setSid(java.lang.String sid) {
		set("sid", sid);
		return (M)this;
	}

	public java.lang.String getSid() {
		return get("sid");
	}

	public M setSname(java.lang.String sname) {
		set("sname", sname);
		return (M)this;
	}

	public java.lang.String getSname() {
		return get("sname");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public M setCardnumber(java.lang.String cardnumber) {
		set("cardnumber", cardnumber);
		return (M)this;
	}

	public java.lang.String getCardnumber() {
		return get("cardnumber");
	}

	public M setPwd(java.lang.String pwd) {
		set("pwd", pwd);
		return (M)this;
	}

	public java.lang.String getPwd() {
		return get("pwd");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

}
