package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public M setAdid(java.lang.String adid) {
		set("adid", adid);
		return (M)this;
	}

	public java.lang.String getAdid() {
		return get("adid");
	}

	public M setAname(java.lang.String aname) {
		set("aname", aname);
		return (M)this;
	}

	public java.lang.String getAname() {
		return get("aname");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public M setCardnumber(java.lang.String cardnumber) {
		set("cardnumber", cardnumber);
		return (M)this;
	}

	public java.lang.String getCardnumber() {
		return get("cardnumber");
	}

	public M setPwd(java.lang.String pwd) {
		set("pwd", pwd);
		return (M)this;
	}

	public java.lang.String getPwd() {
		return get("pwd");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

}
