package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseChoiceQuestion<M extends BaseChoiceQuestion<M>> extends Model<M> implements IBean {

	public M setCId(java.lang.Integer cId) {
		set("c_id", cId);
		return (M)this;
	}

	public java.lang.Integer getCId() {
		return get("c_id");
	}

	public M setCQuestion(java.lang.String cQuestion) {
		set("c_question", cQuestion);
		return (M)this;
	}

	public java.lang.String getCQuestion() {
		return get("c_question");
	}

	public M setCChoicea(java.lang.String cChoicea) {
		set("c_choiceA", cChoicea);
		return (M)this;
	}

	public java.lang.String getCChoicea() {
		return get("c_choiceA");
	}

	public M setCChoiceb(java.lang.String cChoiceb) {
		set("c_choiceB", cChoiceb);
		return (M)this;
	}

	public java.lang.String getCChoiceb() {
		return get("c_choiceB");
	}

	public M setCChoicec(java.lang.String cChoicec) {
		set("c_choiceC", cChoicec);
		return (M)this;
	}

	public java.lang.String getCChoicec() {
		return get("c_choiceC");
	}

	public M setCChoiced(java.lang.String cChoiced) {
		set("c_choiceD", cChoiced);
		return (M)this;
	}

	public java.lang.String getCChoiced() {
		return get("c_choiceD");
	}

	public M setCAnswer(java.lang.String cAnswer) {
		set("c_answer", cAnswer);
		return (M)this;
	}

	public java.lang.String getCAnswer() {
		return get("c_answer");
	}

	public M setTrueTimes(java.lang.Integer trueTimes) {
		set("true_times", trueTimes);
		return (M)this;
	}

	public java.lang.Integer getTrueTimes() {
		return get("true_times");
	}

	public M setAllTimes(java.lang.Integer allTimes) {
		set("all_times", allTimes);
		return (M)this;
	}

	public java.lang.Integer getAllTimes() {
		return get("all_times");
	}

}
