package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFillQuestion<M extends BaseFillQuestion<M>> extends Model<M> implements IBean {

	public M setFId(java.lang.Integer fId) {
		set("f_id", fId);
		return (M)this;
	}

	public java.lang.Integer getFId() {
		return get("f_id");
	}

	public M setFQuestion(java.lang.String fQuestion) {
		set("f_question", fQuestion);
		return (M)this;
	}

	public java.lang.String getFQuestion() {
		return get("f_question");
	}

	public M setFAnswer(java.lang.String fAnswer) {
		set("f_answer", fAnswer);
		return (M)this;
	}

	public java.lang.String getFAnswer() {
		return get("f_answer");
	}

	public M setTrueTimes(java.lang.Integer trueTimes) {
		set("true_times", trueTimes);
		return (M)this;
	}

	public java.lang.Integer getTrueTimes() {
		return get("true_times");
	}

	public M setAllTimes(java.lang.Integer allTimes) {
		set("all_times", allTimes);
		return (M)this;
	}

	public java.lang.Integer getAllTimes() {
		return get("all_times");
	}

}
